import Cocoa

/// Copy a string to the system clipboard.
///
/// Marks the pasteboard entry as transient/concealed/auto-generated so
/// well-behaved clipboard managers (Maccy, Paste, Raycast, Alfred, …) skip
/// it instead of archiving the OTP to disk forever. See <http://nspasteboard.org>.
func copyToClipboard(_ text: String) {
    let pasteboard = NSPasteboard.general
    pasteboard.clearContents()
    pasteboard.setString(text, forType: .string)
    pasteboard.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))
    pasteboard.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"))
    pasteboard.setString("", forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
}
